### ISSUE TITLE
No rerender by value or history change

### ISSUE THREAD

**Issue by RunRanger** [valtiojs/valtio-history#10]
I'm not sure if this is intentional, but I have the case that my Redo/Undo buttons are in their own component. The only problem is that canRedo/canUndo are not re-executed because no state changes. Using the history object does not help either.

Rerendering is only possible when the value is added.

Valtio Example restructured to fit to this use case:
https://codesandbox.io/p/sandbox/valtio-history-example-v0-forked-gl5t69?file=%2Fsrc%2FUndoRedo.tsx%3A4%2C1

**Comment by lwhiteley** [comment]
Hi @RunRanger , 

i ran into the same issue as well.

useSnapshot internally uses a proxyMap and if the proxy is not registered in time there for this setup, it doesnt give updates within a react render with Isolated components such as this

https://github.com/valtiojs/valtio-history/blob/undo-redo-subscribe/examples/typescript-001/src/app/text-tracker.tsx

The above link is an example of a workaround where the useSnapshot is called early in the app tree to do an initial bootstrap and then everything works as expected.

Ive also updated your example to showcase the same
https://codesandbox.io/p/sandbox/valtio-history-example-v0-forked-yrrw7d?file=%2Fsrc%2FApp.tsx%3A8%2C26

-----

cc: @dai-shi : Is there any official recommendation for this scenario or is it a bug that should be reported and fixed for `valtio`?

**Comment by dai-shi** [comment]
Sorry, I'm not following the problem. Can you show the issue with a smaller example? One file with as few lines as possible, without valtio-history.

**Comment by RunRanger** [comment]
> Hi @RunRanger ,
> 
> i ran into the same issue as well.
> 
> useSnapshot internally uses a proxyMap and if the proxy is not registered in time for this setup, it doesnt give updates within a react render with isolated components such as this
> 
> https://github.com/valtiojs/valtio-history/blob/undo-redo-subscribe/examples/typescript-001/src/app/text-tracker.tsx
> 
> The above link is an example of a workaround where the useSnapshot is called early in the app tree to do an initial bootstrap and then everything works as expected.
> 
> Ive also updated your example to showcase the same https://codesandbox.io/p/sandbox/valtio-history-example-v0-forked-yrrw7d?file=%2Fsrc%2FApp.tsx%3A8%2C26
> 
> cc: @dai-shi : Is there any official recommendation for this scenario or is it a bug that should be reported and fixed for `valtio`?

Unfortunately your sandbox is private.

Calling useSnapshot in the App component makes it work but it also rerenders the App component everytime.

**Comment by RunRanger** [comment]
> Sorry, I'm not following the problem. Can you show the issue with a smaller example? One file with as few lines as possible, without valtio-history.

The problem occurs if you seperate the components. A component which just uses canUndo/canRedo or history won't update on itself. To have a workaround you have to listen to value also to update the component for undo/redo:
https://codesandbox.io/p/sandbox/valtio-history-example-v0-forked-8mm8z5?file=%2Fsrc%2FApp.tsx%3A6%2C42

**Comment by lwhiteley** [comment]
ok Ive managed to narrow it down..

No re-renders happen in a component that does not utilize the `value` property of the proxy.

My hunch is that due to the functions accessing property wrapped with `ref`.. then no re-rendered happen when only using these methods


see sandbox: https://codesandbox.io/p/sandbox/valtio-history-example-v0-forked-ghg8fx?file=%2Fsrc%2FApp.tsx%3A20%2C7-20%2C22

Notice that only ` <UndoRedo2 />` gets re-rendered when changing the text just by accessing the `value` property; even though its not even used


------
Sidenote:
codesandbox seems to create forks as drafts now and private by default..the above sandbox is also private

**Comment by dai-shi** [comment]
Here's livecodes version: https://livecodes.io/?x=id/tpq4ia5b2k2

Would it be impossible to create a reproduction without valtio-history?

**Comment by lwhiteley** [comment]
let me attempt to reproduce it

**Comment by dai-shi** [comment]
stackblitz is another tool you can use.

**Comment by lwhiteley** [comment]
i would have to create a simplified version of proxyWithHistory. As the core problem may  just be how valtio treats `ref` anyway

**Comment by lwhiteley** [comment]
let me know if thats enough

https://livecodes.io/?x=code/N4IgLglmA2CmIC4QFUB2kawCYAIAKATgPYBWsAxmCADQhawDO5BEADpEaoiDSABawAhlm4AeALawwgnOT6CCDKQF4AOigAqAMQC0ADnU4A9AD5VqCVJmpBktSABuEWAHdWRAmEPlOYWOnsXCCwwPmV6J3JYHSCQvmocCFQoCEFoHSY02GUARgA6AAZDU14+MHFoAEEwMEVuaEFUAHN7f28GhgZ7dV5pJoZEAG0AXVpBSggHWABRLCgPbiYWdl5xBQBrAFdWRFAG5s3BJvgkMoreH3R-KiQQAF9aBjAATzhdkH2mw+Puck6L3zXbh5SqsVg4YDmHA4ABmvh0MNsEGgzwQOHUAAlYNAppByDIAHKwTawdQJBiNBgZWAsGEAbihOD8AA8wDo0hAmqg0VErgQGag7uZzHkknCIYy5gxWA1UbC4MyBdCSJsnhAYc8dJc-OgedcaUqcKxhHNmmicgRYOIBULUCLsPMCBLUNCpTLBHKYQrDWsCE0kmiCjhBJswERDbFQmi9AUAKSGr2wZk6OaWiacHlEaCbcSoH0Kf2oHQAIyINSI4kDeQArJbreZbfdHsw2Dc9o0vkcTuAGMyAVd0NwIOJ3J4cAAlISUWHEcTokCW8ZeEAC4ejsDO6GbVBPQTFuAAfWLm2RWEIRGZzy02-TLsEDBwx9P58v19Qt+ojNYxEvn5dOEtGE-2hBgbFYBg+DLYCcAYTZiyWCBi1gaDVVgABlMCIKghsZwrecHDSDh1AFYV304J4jR-Z4AFkiHIdYcGUHAAAoCOzWAAEpGJMSE7X-S4KO-C9ngAeWLMhpyYoTL2Y3joTYkloL4CAng8OVAOYkYOOg-FUDQLAiDRZiuOUExKOEsSJLAPJlNUghnjyOBmlCHAzIKHTGknAyjJMszpNE8SKGs2yw3sxz-CaFy3OgkC4IQpCfO4xloVi+CWyQ5j-MsoKEmYohwN8zcUpSrLAsoGyVNChzWFVPhmJyDjkpSu5tIbDiSNQUqrLyWC0pYDL2vMS0wE2AgXS6oKcNIpN11kciNxZMAX2eRjzMvWj6Nkxa0QAclCFTEgfBgK1gGDbBlU7Fp2lrpuZWb6ERTZoA3GEbw4F1QVYYyiuG0aXWYprRDmBxZA6BgCVsbJ1E+9QzH-YrRD4AAmExZkdHAghckK1NEIxkbh4roVEDQkw3UwmqJ4GCcJon9KILyiGMamEaMKnSJpoHJmZwnRDphmkaZimcFxtn4eF1mucZQbBVIgSN22LBBD8EnWVW5jYCmXUJynayAGF5GaGZNbAUQMQ0aiABkVbASpF2mOBJHQExfMZZjFuWvIFNgPJFtWjXrh9gspE9tISWl8xXvfd6cDR0Lvrkuadw3YAcC9nA7lW1CMMEcDILAN3SeW6XoV+saWMB7nKcmUH73ByHWjmULYaFonFoUIRU9D7JgC9n3SYz4gXC6YAABYM84fWO27hWldga2M-JsWiYlhxudx6npdtCO3ogTgcGt+PGTliEcGx+z08zpRs9zssC9ZIvDVL-6K6FzmQfIMGIbsdQxSIZul5SqIaUjRK6EzkFPB8wAz4OScpFPgtoabL2AagUBItJYANELHDwgsxbryljaUikdbw4D5tgIgh9+LzRPrpOmCRdIMwvkxLOmE853yWlRYuAEpB-XLrg1Bx5ywuilHuOAWBlDAAAIQ0NQAZYydxQHQjpq-IwAiwwoNfqovewj9zYHEVIzyZC5EKO1gZZRmj1G4MXtCTe28o67xdKQgySMKHQmPinWQjRaEeNQAzBIacM5MKviw2+7sOGP24WXAGfCNGhjUTgbRoi9HSNkRxeRLcSEyL-hglRsTOD8Nyf+BJujJH0MMak4xDMzEFLXlYnANiuAPBAE8V4jABBSAGAgEYzZlhgA6V0kAfwGCEEYFIbgvAhJRE6B4PpowBmqjDOINCUhIDNA6cARpa4PC9N2I0l4rBGA7NoH4J4ayPgdm+N2PZjAWwrFoNqIEtxGlTEUPY7gSMABsvBFwGVQCiRAiJoBKDGNAaARAXAWw7JPQ2iBaiKRAOIIg9BuCvRBb0IgWZTn+BEdgbgaRoC8CXJMbsAkszwEeNIEaHSBmgqUCIRpAAvdF4hEA5DuEAA

**Comment by lwhiteley** [comment]
>  Did I make it a function originally?

yep was always a function

**Comment by lwhiteley** [comment]
using a getter might be tricky i guess.. doesnt behave well the last time i tried

**Comment by dai-shi** [comment]
> yep was always a function

Oh,  yeah...
It's not easy to make it a value because it loops infinitely (maybe `ops` help).

> using a getter might be tricky i guess

yeah, but it might work. 
https://github.com/pmndrs/valtio/blob/9593184ad94928e54382bfd0e0beb7d1416eb6fe/docs/guides/computed-properties.mdx
Read it carefully. You need `this` to make it work correctly I guess.

**Comment by lwhiteley** [comment]
initial proposal made: https://github.com/valtiojs/valtio-history/pull/11

**Comment by lwhiteley** [comment]
version 0.3.0 has been released to npm
