### ISSUE TITLE
Slowdown of intellisense in VSCode

### ISSUE THREAD

**Issue by RunRanger** [valtiojs/valtio-history#12]
``Hello everybody,

i'm not sure if it's reproducable but intellisense slows down immediatly after opening a .ts file which has the following import:
`import { proxyWithHistory } from 'valtio-history';`

An suggestion can take up to multiple minutes or get stucks forever. Removing the line and restart vscode intellisense works totally fine on this file. I will try to reproduce it later

Versions:
`    "valtio": "^1.13.2",
    "valtio-history": "^0.3.2",
    "typescript": "^5.4.2"
`
node: v18.19
npm: 10.5
turbo: 1.12.4 (but valtio is installed in a workspace, not whole monorepo)

Note: Issue existed also before 0.3.2, just updated it in case it would be fixed.

tsconfig:
```{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "types": ["vite/client"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": false,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "composite": true
  },
  "include": [
    "src" ,
    "src/i18n/*.json"
  ],
  "exclude": ["node_modules"],
  "extends": "./tsconfig.paths.json",
  "references": [{ "path": "./tsconfig.node.json" }]
}

**Comment by RunRanger** [comment]
I've tried to replicate it to a small vite-project but couldn't replicate it yet.

Nice to know, if i copy the source file from valtio-history into my own project and import it, intellij is as fast as normal.
So it's something with the npm package.

**Comment by panukettu** [comment]
This is definitely happening. Reason is the massive type definition output for `getNode`: 
![image](https://github.com/valtiojs/valtio-history/assets/18403470/d1880714-5908-45d7-87a7-be8052cf1de8)

It probably should be eg. `getNode: (index: number) => HistoryNode<V> | undefined`

**Comment by lwhiteley** [comment]
version 0.3.5 was published to npm.

check it out and let me know if this problem is resolved for you

**Comment by RunRanger** [comment]
Seems to be working now. Thank you @panukettu and @lwhiteley !
