### ISSUE TITLE
History not updating when a state property is set to undefined

### ISSUE THREAD

**Issue by fabio-grieco** [valtiojs/valtio-history#13]
### Link to reproduce
[Sandbox](https://codesandbox.io/p/sandbox/valtio-history-issue-wkpjft)

### Current behavior
History isn't updated when any state property is set to `undefined`.

### Expected behavior
I would expect history to be updated even when any state property is set to `undefined`.

**Comment by lwhiteley** [comment]
the sandbox is pivate, please make it public

**Comment by fabio-grieco** [comment]
uh sorry, now is public
