### ISSUE TITLE
0.2.0+ versions throw error in useSnapshot

### ISSUE THREAD

**Issue by kfrp** [valtiojs/valtio-history#9]
Hi, I use CDNs to import the latest versions of valtio, valtio/utils and valtio-history into my code, and today while trying out a bit of code from last month I noticed that the latest version of `proxyWithHistory` is throwing an error when I use it in a `useSnapshot` call. 

The error occurs on [this line](https://github.com/pmndrs/valtio/blob/baba86789712f5a0857b2b7580248ffc0f8934e0/src/vanilla.ts#L401) in the valtio lib. Specifically, it logs the warning from the line before, and then logs an error that "proxyState is not iterable" (it shows as undefined in the debugger). When I tried to do a `getVersion` call on the object returned from `proxyWithHistory`, I got undefined there as well. 

I have reverted to 0.1.0, which does not throw this error, and `getVersion` also returns a version for my proxy with history. 

Reporting here to see if you can track it down or let me know if I'm doing something wrong.

**Comment by lwhiteley** [comment]
Hi, thanks for submitting the issue.

is it possible for you to provide a small reproduction showing the issue.

**Comment by kfrp** [comment]
Sorry I think it's an error in the way the library is compiled on esm.sh, because when I compiled it myself using vite it worked fine. Closing!
